# Generated by Django 2.2 on 2022-02-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('idade', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveKeyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=200)),
                ('resultado_1', models.CharField(max_length=300)),
                ('resultado_2', models.CharField(max_length=300)),
                ('resultado_3', models.CharField(max_length=300)),
                ('resultado_4', models.CharField(max_length=300)),
                ('resultado_5', models.CharField(max_length=300)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Integrante')),
            ],
        ),
    ]
