# Generated by Django 2.2 on 2022-02-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivekeyresult',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='register.Integrante'),
        ),
        migrations.AlterField(
            model_name='objectivekeyresult',
            name='resultado_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='objectivekeyresult',
            name='resultado_3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='objectivekeyresult',
            name='resultado_4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='objectivekeyresult',
            name='resultado_5',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
